server:
  port: 8080

spring:
  cache:
    type: caffeine
  application:
    name: bank-transaction-service

logging:
  level:
    root: INFO
    com.bank.transaction: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true