apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-transaction-service
  labels:
    app: bank-transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-transaction-service
  template:
    metadata:
      labels:
        app: bank-transaction-service
    spec:
      containers:
        - name: bank-transaction-service
          image: your-docker-repo/bank-transaction-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
      restartPolicy: Always