# 执行docker build制作好最新版本镜像后，部署到腾讯云ECS搭建的minikube环境。
# 暂未实现：网络原因，没有找到合适的用来存储docker 镜像的仓库。
name: CD for Main Branch

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Tencent ECS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TENCENT_SSH_KEY }}
          SERVER_IP: ${{ secrets.TENCENT_ECS_IP }}
        run: |
          echo "暂未实现"